# name of the program (Minix service)
PROG=lab2 

# source code files to be compiled
SRCS = lab2.c

# additional compilation flags
# "-Wall -Wextra -Werror -I . -std=c11 -Wno-unused-parameter" are already set
CFLAGS += -pedantic

# Library name and source files for the timer library
LIB_NAME = libtimer.a
LIB_SRCS = timer.c utils.c
LIB_OBJS = ${LIB_SRCS:.c=.o}

# list of library dependencies (for Lab 2, only LCF library)
DPADD += ${LIBLCF} ${LIB_NAME}
LDADD += -llcf -L. -ltimer

# list of files to be removed with "make clean"
CLEANFILES += ${LIB_OBJS} ${LIB_NAME}

# default target: builds everything
all: lib
lib: ${lIB_OBJS}
	ar rcs ${LIB_NAME} ${LIB_OBJS
	}
# ^ ATENÇÃO: A linha acima TEM de começar com um TAB, não espaços!

# include LCOM's makefile that does all the "heavy lifting"
.include <minix.lcom.mk>
